name: My first workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Myfrstjob:
   runs-on: ubuntu-latest
   steps:
     - run: |
         echo "Hello Worlds "
         echo "This is multiple line implementations"
