name: My first workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        require: true
      logLevel:
        description: 'Log level'
        type: choice
        options:
          - info
          - warning
          - debug
      tag:
        description: 'Apply tag after successful test run'
        required: true
        type: boolean
      environment:
        description: 'Environment to run tests against'
        required: true

jobs:
  Myfrstjob:
   runs-on: ubuntu-latest
   steps:
     - run: |
         echo "Hello Worlds "
         echo "This is multiple line implementations"
