name: Test on Push

on:
  push: 
    branches:
      - main 
  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
    
    - name: Setup Elixir 
      uses: erlef/setup-beam@v1
      with: 
        version-file: .tool-version
        version-type: strict 

    - name: Install dependencies 
      run: mix deps.get 
    
    - name: Check formatting 
      run: mix format --check-formatted

    - name: Create and migrate database 
      run: |
        mix ecto.create
        mix ecto.migrate 

    - name: Run test
      run: mix test



















# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
    # inputs:
    #   homedrive:
    #     description: 'The home drive on the machine'
    #     require: true
    #   logLevel:
    #     description: 'Log level'
    #     type: choice
    #     options:
    #       - info
    #       - warning
    #       - debug
    #   tag:
    #     description: 'Apply tag after successful test run'
    #     required: true
    #     type: boolean
    #   environment:
    #     description: 'Environment to run tests against'
    #     required: true

# jobs:
  # Myfrstjob:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - run: |
  #        echo "Hello Worlds "
  #        echo "This is multiple line implementations"
  # job_1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: "echo Job: ${{github.job}}"
  # job_2:
  #   runs-on: ubuntu-latest
  #   needs: job_1
  #   steps:
  #     - run: "echo Job: ${{github.job}}"
  # job_3:
  #   runs-on: ubuntu-latest
  #   needs: job_1
  #   steps:
  #     - run: "echo Job: ${{github.job}}"
  # job_4:
  #   runs-on: ubuntu-latest
  #   needs: [job_2, job_3]
  #   steps:
  #     - run: "echo Job: ${{github.job}}"
